### ISSUE TITLE
HTTP client: Handle 404

### ISSUE THREAD

**Issue by maximevince** [tass-belgium/picotcp-modules#9]
Using the http-client-demo, and querying http://httpbin.org/,
and then choosing the "1 = get connection close" header,
results in a 404-response, but the demo or http lib still tries to read data from a body that has length 0.
@robbinvandamme

**Comment by VincentDeHaen** [comment]
Similar behaviour:
sending http package with body content. 
http lib receives the header ok but says that body length is 0 and keeps on trying to read the body.
@robbinvandamme

**Comment by robbinvandamme** [comment]
HTTLIB now also handles the body of the http error-responses.

**Comment by robbinvandamme** [comment]
"Content-Length" in response was spelled wrong ("Content-length").
